### ISSUE TITLE
Not able to get aws credentials with CLI

### ISSUE THREAD

**Issue by vivekgkwd** [physera/onelogin-aws-cli#153]
Hi,

We are getting the following the error :

This was working fine over a year and suddenly stopped working for everyone in the org.

➜  ~ java -jar ~/onelogin/onelogin-aws-cli.jar -a masked_account_id -d d11 -u masked_emailId --duration 43200 -r us-east-1 -p load

OneLogin AWS Assume Role Tool

Exception in thread "main" OAuthProblemException{error='Unauthorized', description='Authentication Failure', uri='null', state='401', scope='null', redirectUri='null', responseStatus=401, parameters={}}
	at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:59)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateErrorResponse(OAuthClientValidator.java:63)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validate(OAuthClientValidator.java:48)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.validate(OAuthClientResponse.java:127)
	at com.onelogin.sdk.conn.OneloginOAuthJSONAccessTokenResponse.init(OneloginOAuthJSONAccessTokenResponse.java:27)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:101)
	at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:60)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:120)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponseFactory.java:82)
	at com.onelogin.sdk.conn.OneloginURLConnectionClient.execute(OneloginURLConnectionClient.java:75)
	at com.onelogin.sdk.conn.Client.updateTokens(Client.java:3799)
	at com.onelogin.sdk.conn.Client.getAccessToken(Client.java:191)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:208)

**Comment by kevinRR** [comment]
i am also facing the same issue 
<img width="1426" alt="Screenshot 2022-05-25 at 16 24 07" src="https://user-images.githubusercontent.com/16461178/170285666-9ecbb0b6-3b0b-45a0-a40e-be7f25c3e923.png">

**Comment by sol-aserputov** [comment]
any updates?

**Comment by sol-aserputov** [comment]
@slycoder @drewsonne @amenon
