### ISSUE TITLE
missing requirement: configparser

### ISSUE THREAD

**Issue by f0o** [physera/onelogin-aws-cli#25]
Title states it.

```
$ pip install onelogin-aws-cli
$ onelogin-aws-cli -c
Traceback (most recent call last):
  File "/bin/onelogin-aws-login", line 7, in <module>
    from onelogin_aws_cli import OneloginAWS
  File "/usr/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 3, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by f0o** [comment]
Solved by using `pip3` instead of `pip`. Perhaps dont make it available through `pip` without having python3 in the first place...
