### ISSUE TITLE
Unexpected EOF while parsing API Client ID

### ISSUE THREAD

**Issue by f0o** [physera/onelogin-aws-cli#26]
Any ideas?

```
onelogin-aws-login -c
Configure Onelogin and AWS


Pick a Onelogin API server:

1. https://api.us.onelogin.com/
2. https://api.eu.onelogin.com/

? 2

Onelogin API credentials. These can be found at:
https://admin.us.onelogin.com/api_credentials
Onelogin API Client ID: abcd
Traceback (most recent call last):
  File "/bin/onelogin-aws-login", line 24, in <module>
    OneloginAWS.generate_config()
  File "/usr/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 229, in generate_config
    default["client_id"] = input("Onelogin API Client ID: ")
  File "<string>", line 1
    abcd
        ^
SyntaxError: unexpected EOF while parsing

```

**Comment by f0o** [comment]
#25
