### ISSUE TITLE
SyntaxError on login attempt

### ISSUE THREAD

**Issue by f0o** [physera/onelogin-aws-cli#27]
```
$ onelogin-aws-login
Onelogin Username: user@domain.tld
Traceback (most recent call last):
  File "/bin/onelogin-aws-login", line 33, in <module>
    api.save_credentials()
  File "/usr/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 184, in save_credentials
    self.assume_role()
  File "/usr/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 173, in assume_role
    self.get_role()
  File "/usr/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 146, in get_role
    self.get_arns()
  File "/usr/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 125, in get_arns
    self.get_saml_assertion()
  File "/usr/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 83, in get_saml_assertion
    self.username = input("Onelogin Username: ")
  File "<string>", line 1
    user@domain.tld
                    ^
SyntaxError: invalid syntax
```

**Comment by f0o** [comment]
#25
