### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by evfurman** [physera/onelogin-aws-cli#5]
Hey guys, I get a bad request returned when trying to authenticate. Have you experienced this issue? Know how to fix?

```
[root@bastion-prod ~]# onelogin-aws-login
Onelogin Username: evan.furman
Onelogin Password:
Traceback (most recent call last):
  File "/usr/local/bin/onelogin-aws-login", line 26, in <module>
    api.save_credentials()
  File "/usr/local/lib/python3.4/site-packages/onelogin_aws_cli/__init__.py", line 140, in save_credentials
    self.assume_role()
  File "/usr/local/lib/python3.4/site-packages/onelogin_aws_cli/__init__.py", line 115, in assume_role
    self.get_saml_assertion()
  File "/usr/local/lib/python3.4/site-packages/onelogin_aws_cli/__init__.py", line 86, in get_saml_assertion
    res = self.request("api/1/saml_assertion", headers, params)
  File "/usr/local/lib/python3.4/site-packages/onelogin_aws_cli/__init__.py", line 57, in request
    raise Exception("Error: {}".format(res.json()))
Exception: Error: {'status': {'code': 400, 'message': 'bad request', 'type': 'bad request', 'error': True}}
```

Thanks!

**Comment by slycoder** [comment]
I was futzing around with parameters to see what could cause this and the only way for me to get this to happen was to blank out the subdomain and/or app id.  Can you check that those are set correctly?

**Comment by cameronmarlow** [comment]
Closing this out - let me know if you can repro
